# Generated by Django 3.2.8 on 2021-10-30 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPScanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=15)),
                ('date', models.DateField(verbose_name='Scanned Date')),
            ],
        ),
        migrations.DeleteModel(
            name='ScannerIP',
        ),
    ]
