# Generated by Django 3.2.8 on 2021-10-30 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0002_auto_20211030_1034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ipscanner',
            name='date',
        ),
    ]
