# Generated by Django 3.2.8 on 2021-10-30 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0003_remove_ipscanner_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IPScanner',
        ),
    ]
