# Generated by Django 3.2.8 on 2021-10-30 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scanner', '0004_delete_ipscanner'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPScanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=15)),
            ],
        ),
    ]
