# Generated by Django 3.2.8 on 2021-10-30 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0005_ipscanner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IPScanner',
        ),
    ]
